Misc again
e621ng/e621ng pull request #297
Opened 2021-07-22 13:25 UTC by Earlopain

Another one of those pr where I put a bunch of smaller stuff together.

1. Repeatedly clicking on edit on a post would grow the tagbox continuously in size. Fix this by simply resizing the textarea just once on the initial open. Coincidentally this also fixes the tagbox not being correctly resized on initial open because vue completely replaces the element it gets mounted on, throwing the first resize away.
2. Update embed title from `drawn by`to `created by` to account for 3d artwork. I saw this brought up in the discord at some point.
3. Fix some wrong table column on the ip adresses page.
4. Fix html encoding on the ticket index page. For some reason stripping first and truncating after fixes the issue, like it already happens for the title.
![image](https://user-images.githubusercontent.com/14981592/126643713-e0dc50d9-e6e9-48a7-88f7-ecf735cf543b.png)
Stuff still gets correctly html encoded.
5. Editing an artist without a wiki page would always say that note changes happenend. This probably happenend because `notes` is nil while `text` was the empy string.
6. Add to set would always flash up on the posts index, even when not selected. The other two select boxes already behaved correctly. This also adds some padding, like on the other inputs. The code already handles showing the box correctly when it is selected on load.
7. Fix typo on `respond_to` on tag type versions.
8. Make the source buttons on the uploader a bit larger. I always found them a bit to hard to hit.
![image](https://user-images.githubusercontent.com/14981592/126644481-2f6ac924-23d4-40d9-9425-43b1f8f56605.png)
![image](https://user-images.githubusercontent.com/14981592/126644501-5a367965-fd13-4cc6-abcb-9e82a4bf9c57.png)
8. Remove appeals, add stats, db export and avoid posting and link to pools gallery on the sitemap.
9. Remove highchart references from the stats page. Some time ago you removed the needed vendor scripts but the text and some js was still left.
10. Fix wrong wiki link on the uploader. Seems like I fucked this one up im my uploader pr.
11. Filter out duplicate tags on the tag preview. Consider the following: A -> B -> C but also A -> D -> C. C now appears twice in the list.
![image](https://user-images.githubusercontent.com/14981592/126645175-00b1d68b-35c7-46ef-8bd6-a4e3b8de91f2.png)
![image](https://user-images.githubusercontent.com/14981592/126645208-3de05a5e-c324-442c-91e3-d40203152af0.png)

2021-08-03 22:41 UTC, zwagoth requested changes

2021-08-03 22:41 UTC, kiranoot commented on app/models/artist.rb
> +      if notes != text && !text.empty?
This removes logging of when a note is removed. If empty notes are being logged every time then a special check needs to be made.

2021-08-03 22:41 UTC, zwagoth commented on app/views/tickets/index.html.erb
> +					<td class="ticket-subject" title="<%= h(truncate(strip_dtext(ticket.reason), length: 200)) %>"><%= link_to h(truncate(strip_dtext(ticket.subject), length: 200)), action: "show", id: ticket.id %>
I'd ask that you drop this commit for right now and I will investigate and address it further. Subjects probably shouldn't be allowed html, or dtext for that matter.

2021-08-04 10:03 UTC, Earlopain commented
I dropped them both for now. I'll take a look at the artist one at a later date

2021-08-04 12:05 UTC, merged