Danbooru cleanup
e621ng/e621ng pull request #357
Opened 2021-11-24 22:49 UTC by Earlopain

Keeping this as a draft while I still repair some tests.

This looks rather large but not much is actually happening here. I always hated how the tests are mostly useless since there were so many failing you had no chance to see if you actually broke something. Looking at the assertion count also doesn't help you because test failures vary from run to run.

Here are some numbers where I am at right now. Execution time stayed mostly the same, but improved a bit overall. I'll update this as I repair more tests.
master:  `1554 runs, 1994 assertions, 166 failures, 394 errors, 30 skips`
this pr:  `1282 runs, 2209 assertions, 53 failures, 25 errors, 0 skips`

In order to make this work I removed a bunch of danbooru specific code and features that are disabled or unused, including their tests. A large portion of these changes are just removing unsused functionality, removing now unused functions, removing views, removing even more newly unused functions etc.

I removed:
- Source Strategies
- Recommender Service
- Reportbooru
- Reports
- Unused maintanance tasks
- Artist Commentaries
- Post Appeals
- Spam detector
- Ugoira
- Artist Groups
- And a bunch of other smaller things

I image that most of these didn't work anymore anyways since it has been two years since anything has been done to them while the codebase kept evolving. Removing their tests reduced failures/errors by a significant amount already.

Elasticsearch indicies are now prefixed with the environment when not running in production. Sometimes my search broke on development which I think was because it shared the index with test. This might fix this, though I'm not 100% sure. It does at least fix some tests which were failing previously.
I'm not sure how you are supposed to test against elasticsearch, there are still tests which I believe are failing because of it. Droping/Recreating the index on each test would certainly work but it also increases the run duration by way to much.

If you have a local config it now doesn't apply to tests anymore. Disabling limits for development should not lead to broken test.

I also added a new docker service you can use to run the tests more conveniently. Might also be usable on some kind of CI, who knows
`docker-compose run test` runs the whole suite.
`docker-compose run test TEST=unit/models/post_test.rb` runs the tests of only a single file.
`docker-compose run test TEST=unit/models/post_test.rb:42` runs the specific test at that line.

2021-11-27 19:56 UTC, Earlopain commented
Finally got it all working, I've now got zero errors/failures when running all tests, consistently too. Test time increased by ~30 seconds overall for me to 220 seconds for a full run. Probably because of waiting for ealsticsearch when creating/destroying a post which didn't happen before.

![image](https://user-images.githubusercontent.com/14981592/143720447-09cf1a6c-ef0f-4eee-9ba1-5aab50fec82f.png)

2021-12-10 13:21 UTC, zwagoth requested changes
Need to finish up this but sleep first.

2021-12-10 13:21 UTC, kiranoot commented on app/logical/sources/alternates/pixiv.rb
> +      def headers
This value is filled, but does not appear to be used within this commit.

2021-12-10 13:21 UTC, kiranoot commented on app/logical/downloads/file.rb
> +        http_get_streaming(uncached_url, **options)
strategy no longer providers headers?

2021-12-10 13:21 UTC, kiranoot commented on app/logical/d_text.rb
> -  MENTION_REGEXP = /(?<=^| )@\S+/
Part of wrong commit?

2021-12-10 13:21 UTC, kiranoot commented on app/models/post.rb
> -    def distribute_files(file, sample_file, preview_file)
Pretty sure this is still used by the uploader.

2021-12-10 13:21 UTC, kiranoot commented on test/unit/post_flag_test.rb
> +        puts @flag1.errors.full_messages
leftover debug code?

2021-12-10 13:21 UTC, kiranoot commented on docker/danbooru_local_config.rb
> -  class CustomConfiguration < Configuration
This changes the semantics of how this class works. It no longer has all of the methods from the base configuration and moves all the logic into the surrounding wrapper. It seems like it might make sense to allow configuration even during tests, but to spot fill areas that specifically would cause tests to fail during global setup.

2021-12-10 13:21 UTC, kiranoot commented on test/functional/admin/users_controller_test.rb
> +        should "change the leve" do
typo

2021-12-11 13:17 UTC, Earlopain commented on app/models/post.rb
> -    def distribute_files(file, sample_file, preview_file)
The uploader uses `Utils.distribute_files`, not the member method from the post model. This function was only used in rake tasks and fixer scripts.

2021-12-11 13:21 UTC, Earlopain commented on app/logical/sources/alternates/pixiv.rb
> +      def headers
It's used in https://github.com/zwagoth/e621ng/blob/65fed7a800ca5e3adc9f22255cc136ccc290213a/app/logical/downloads/file.rb#L80. A few places still call it strategy, that should probably be renamed

2021-12-11 13:23 UTC, Earlopain commented on app/logical/downloads/file.rb
> +        http_get_streaming(uncached_url, **options)
The header variable was simply unused. The headers are set in `http_get_streaming` and are provided by  `httparty_options`, which includes the headers

2021-12-11 13:25 UTC, Earlopain commented on app/logical/d_text.rb
> -  MENTION_REGEXP = /(?<=^| )@\S+/
Seems like it. Should I move it out or just leave it?

2021-12-11 13:51 UTC, Earlopain commented on docker/danbooru_local_config.rb
> -  class CustomConfiguration < Configuration
I reverted this. Fixing this up would probably be another larger undertaking.

2022-02-03 16:11 UTC, closed without merging