Show all users upload whitelist on sitemap, add "Request" and "Help" to the secondary links on the upload whitelist page.
e621ng/e621ng pull request #421
Opened 2022-07-05 16:13 UTC by faucetlol2

Sitemap
* The upload whitelist link has been moved outside the `if CurrentUser.is_admin?` block so regular users can see the link too.

Upload whitelist
* A "Request" subnav link is now shown in place of the "New" button for non-admins, which links to the upload whitelist request forum.
* A "Help" link is also added, which links to the relevant help page.

This closes #420

2022-07-05 16:35 UTC, Earlopain requested changes
Small nitpick. I won't actually be able to merge this until sometime next week, since I'm on vacation at the moment.

2022-07-05 16:35 UTC, Earlopain commented on app/views/static/site_map.html.erb
> +          <li><%= link_to("Upload Whitelist", upload_whitelists_path) %></li>
Not properly indented. Also, please move it down to the other member visible links, just so they are more grouped together in the code.

2022-07-05 16:35 UTC, Earlopain commented on app/views/upload_whitelists/_secondary_links.html.erb
> +    <% else %>
I would have just added this link for anyone regardless of user level.

2022-07-08 18:20 UTC, faucetlol2 commented on app/views/upload_whitelists/_secondary_links.html.erb
> +    <% else %>
My initial thought was that having both "New" and "Request" on the menu at the same time would be a little confusing, but it makes complete sense that an admin would also want to check that forum to check if any new requests have been made. I removed the else and renamed it to "Requests" which seems a little more fitting.

2022-07-08 18:20 UTC, faucetlol commented on app/views/static/site_map.html.erb
> +          <li><%= link_to("Upload Whitelist", upload_whitelists_path) %></li>
Sorry, done!

2022-07-08 20:14 UTC, Earlopain approved these changes

2022-07-10 20:22 UTC, merged