[Post] Add behavior to add sources using '+source' metatag
e621ng/e621ng pull request #558
Opened 2023-11-05 19:11 UTC by mm12

The `source:` metatag current overwrites all sources when used. This adds behavior for a `+source` metatag that appends a new source to the existing source string, and adds unit tests for it.

2023-11-05 19:57 UTC, faucetlol commented
Is there any reason to use metatags to edit sources rather than just using `post[source_diff]` in the API? I wasn't even aware that `source:` could actually be used for editing.

It does actually seem to give a bypass for issue #554 though, seeing as I'd just be able to do `+source:-https://brokenlink.com` as a tag edit.

2023-11-05 20:19 UTC, mm12 commented
> Is there any reason to use metatags to edit sources rather than just using `post[source_diff]` in the API? I wasn't even aware that `source:` could actually be used for editing.
> 
> It does actually seem to give a bypass for issue #554 though, seeing as I'd just be able to do `+source:-https://brokenlink.com` as a tag edit.
> 
> The metatag name `+source` would, to me, also imply the existence of `-source`, which doesn't exist and probably never could because of technical reasons.

Yes, tag scripts and similar tools can be used to add the same source to multiple posts. This is useful in instances where a site has multiple images on one post, such as Pixiv and Twitter. There is no way to add a source to multiple posts otherwise.
Originally, I called it "addsource", however, that name is inconvenient. I suppose removing sources the same way would be handy, but how exactly that would work with wildcards is not fun to think about.

2023-11-05 21:17 UTC, mm12 commented
> Is there any reason to use metatags to edit sources rather than just using `post[source_diff]` in the API? I wasn't even aware that `source:` could actually be used for editing.
> 
> It does actually seem to give a bypass for issue #554 though, seeing as I'd just be able to do `+source:-https://brokenlink.com` as a tag edit.
> 
> The metatag name `+source` would, to me, also imply the existence of `-source`, which doesn't exist and probably never could because of technical reasons.

I have made a simple example of being able to remove sources. https://github.com/mm12/e621ng/blob/sourceFix_removeExample/app/models/post.rb

However, it doesn't work in the context that adding sources is meant to (tag scripts) - only in the editor

2023-11-15 02:58 UTC, mm12 commented
... ok will fix

2023-11-15 05:38 UTC, mm12 commented
I found the problem - my branches broke because I messed up (proof of concept code leaked between them causing errors). I have re-synced to master and fixed the branch, and everything is passing now.

2023-11-16 01:41 UTC, mm12 commented
I just realized I should add this to `https://github.com/e621ng/e621ng/blob/master/app/logical/tag_query.rb` as well?

2025-07-21 01:42 UTC, jmortiger commented
Looking at `Files Changed`, it looks like this has been added, just not through merging this PR; is that accurate?

2025-07-21 02:18 UTC, mm12 commented
> Looking at `Files Changed`, it looks like this has been added, just not through merging this PR; is that accurate?

No, I don't believe it is:  https://github.com/e621ng/e621ng/blob/851cd5c68a922a39b7b300670b0d988b4c41693e/app/models/post.rb#L824-L837

I need to rebase, though.

2025-09-24 00:47 UTC, mm12 commented
Will try to migrate to `^source:([""]?)(.*)\1$` (or something along those lines) to solve both of these at once. Making the tests a bit better to make sure that it works as intended too.

2026-05-29 22:48 UTC, Sindrake requested changes
Looks good, but could use more tests, just for safety's sake.
- `+source:"https://example.com"`
- `+source:none` (would it just append "none" to sources?)
- multiple `+source:` in one string

2026-05-29 23:39 UTC, mm12 commented
> Looks good, but could use more tests, just for safety's sake.
> 
>     * `+source:"https://example.com"`
>     * `+source:none` (would it just append "none" to sources?)
>     * multiple `+source:` in one string

Well a partial rewrite of a small PR is probably fine

2026-06-01 18:50 UTC, Sindrake approved these changes
lgtm

2026-06-01 18:51 UTC, merged