Alias antecedent ignore
e621ng/e621ng pull request #698
Opened 2024-08-03 15:03 UTC by DontTalkToMeThx

Fixes the issue present in #329.

Invalid tags that already exist should be aliased away to the valid tags where possible, however the tag validator prevents users from making alias requests with antecedent names that it considers invalid.

This PR allows antecedent names on aliases to skip most of the validation sequence, except for checking for blanks, and checking for tags starting with `-`, which would break the tag string diff.

This will also allow us to create aliases for non-english artists to the english representation of their name, which could prevent people not tagging them, or tagging them improperly as a helpful side effect.

2024-08-04 20:24 UTC, DontTalkToMeThx commented on app/models/tag_implication.rb
Debating if we should even have this, but as it currently stands, implications disabled ascii check, so moving it here is to maintain that feature.

2024-08-04 20:25 UTC, DontTalkToMeThx commented on app/models/tag_implication.rb
> +  validates :antecedent_name, tag_name: { disable_ascii_check: true }, if: :antecedent_name_changed?
Debating if we should even have this, but as it currently stands, implications disabled ascii check, so moving it here is to maintain that feature.

2024-11-14 17:05 UTC, Tarrgon commented
Now that I think about it, if we allow zero-width spaces in alias antecedents, we should highlight them in the forum post/alias view for admins.

2025-09-23 20:52 UTC, Sindrake requested changes
I am not sure if I agree with how this is implemented.

I would reduce the number of rules that can be bypassed like this to the absolute minimum.
Just the ones that are _currently_ causing issues or are waiting to be aliased – like the colon `:` character from the original issue, the peso `$` sign, backslash `\`, and non-acii characters. 

If more issues come up in the future, we can add a bypass for those later.

2025-09-24 13:15 UTC, Tarrgon commented
recheck

2025-09-24 14:18 UTC, Sindrake approved these changes

2025-10-02 14:53 UTC, Sindrake approved these changes

2025-10-02 14:56 UTC, merged