[StaffNotes] Add updating and deleting
e621ng/e621ng pull request #823
Opened 2024-12-10 23:42 UTC by clragon

This PR adds updating and deleting staff notes. 
It slightly changes the UI.
It also moves the endpoint to /staff_notes, which felt more appropriate.

Modifying staff notes always triggers a new mod action which contains the full details of the modification.
These mod actions' details are only visible to mods.

staff notes cannot be destroyed currently.

![image](https://github.com/user-attachments/assets/66e4952d-3ddb-4c47-9c0f-3cbaef125216)

2024-12-12 17:44 UTC, DonovanDMC commented
This pr looks to make destroying possible via the api but without any associated modaction
I'm also not a fan of the modactions being visible to people at all, they ideally shouldn't know we're creating notes in the first place rather than just hiding details

2024-12-12 18:52 UTC, clragon commented
got it, I'll move the files and rip out the code for destroying all together. 

I guess I can look into just excluding these mod actions from the query for non staff users, although this seems, well, unorthodox to me, considering even IP bans are part of the publicly visible mod actions. 
to be honest I dont think any mod actions need to be visible whatsoever, but I know thats a more niche opinion.

2024-12-16 00:25 UTC, DonovanDMC commented
> considering even IP bans are part of the publicly visible mod actions

(FWIW I also moved those out of the modactions in my own code)
I also don't think those should be in the mod actions but that's an argument for another day

2025-01-12 05:30 UTC, Sindrake requested changes

2025-01-12 05:30 UTC, Sindrake commented on app/models/staff_note.rb
> +    return true if creator_id == user.id || user.is_admin
This should be `user.is_admin?`

2025-01-12 05:30 UTC, Sindrake commented on app/views/staff_notes/_search.html.erb
> +  <%= f.user :updater %>
This does not work, since `updater_name` is not a permitted search param.

2025-01-13 03:27 UTC, Sindrake approved these changes

2025-01-13 03:28 UTC, merged